# Site
title:              Joshua Rain(Cao Yuchen)
bio:                'Computer Vision & Graphics, SLAM, ML, AR/VR, <br><br> Photography, Game Develop, Screenplay, Graphic Design.'
description:        "Welcome! This is Joshua's personal website."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
profile:            'assets/img/CaoYuchen.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://caoyuchen.github.io
# url:                /.

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

gist:
  noscript: false

# Comments
disqus_shortname:   JoshuaRain

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              caoyuchen.joshua@gmail.com
# twitter:            username
# facebook:           https://www.facebook.com/caoyuchen.joshua
github-url:         CaoYuchen
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           yuchen-cao-022378117
#xing:              username
instagram:          joshua_cyc
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, _posts]

# Plugins
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
